global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'playlister'
    static_configs:
      - targets: ['app:8000']
        labels:
          app: 'playlister'
          environment: 'production'
    metrics_path: '/metrics'
    scrape_interval: 10s
