global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'playlister-local'
    static_configs:
      - targets: ['app:8000']
        labels:
          app: 'playlister'
          environment: 'local'
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'playlister-azure'
    static_configs:
      - targets: ['playlister-webapp.azurewebsites.net']
        labels:
          app: 'playlister'
          environment: 'azure-production'
    metrics_path: '/metrics'
    scrape_interval: 15s
    scheme: https
